version: '3.7'

services:
  db:
    image: postgres:latest
    container_name: db
    restart: always
    environment:
        POSTGRES_USER: medicarUser
        POSTGRES_PASSWORD: medicar123
        POSTGRES_DB: medicarDb
    ports:
      - 5432:5432

    volumes:
      - pg-data:/var/lib/postgresql/data
  
  api:
    build: ./backend/
    container_name: medicar-api
    environment:
      DJANGO_ALLOWED_HOSTS: localhost 127.0.0.1 [::1] 0.0.0.0 * 
      SQL_ENGINE: django.db.backends.postgresql
      DB_NAME: medicarDb
      DB_USER: medicarUser
      DB_PASSWORD: medicar123
      DB_HOST: db
      DB_PORT: 5432

    volumes:
      - app:/django_medicar_api
    ports:
      - "8000:8000"
    depends_on: 
      - db

volumes:
  pg-data:
  app: