version: '3.7'

services:
  postgres:
    image: postgres:latest
    container_name: medicar-postgres
    restart: always
    environment:
        POSTGRES_USER: medicarUser
        POSTGRES_PASSWORD: medicar123
        POSTGRES_DB: medicarDb
    ports:
      - 5432:5432
    volumes:
      - pg-data:/var/lib/postgresql/data
  
volumes:
  pg-data: